### ISSUE TITLE
npm install fails with error code 1

### ISSUE THREAD

**Issue by dusskapark** [Hugo-Dz/figma_autoname_client_app#4]
Hi, Thanks for sharing your project!

I'm Joo and I also have been interested in adopting TFJS and AI into Figma ([here](https://github.com/dusskapark/figma-ml) is my previous experiments)

Anyway, I am trying to install using `npm install`, but it fails with the error code 1.
I have tried it on Node.js 18.16.0(LTS) and 20.3.0(latest), but both failed.
If I try to install it using `yarn`, it does not fail, but it fails when I run `npm run dev`.
I would appreciate if you can help me to resolve this issue.

Here is the log:

```
654 verbose pkgid node-sass@7.0.0
655 verbose cwd /Users/jude.park/Sites/figma_autoname_client_app
656 verbose Darwin 22.5.0
657 verbose node v20.3.0
658 verbose npm  v9.6.7
659 error code 1
660 error path /Users/jude.park/Sites/figma_autoname_client_app/node_modules/node-sass
661 error command failed
662 error command sh -c node scripts/build.js
```

The important part of the log is the error code 1 and the command `node scripts/build.js`.

I think the problem is caused by `node scripts/build.js` command.

I would appreciate if you can help me to resolve this issue.

Thank you.

<img width="1411" alt="Screenshot 2023-06-11 at 1 09 57 PM" src="https://github.com/Hugo-Dz/figma_autoname_client_app/assets/4177529/50d1b4d2-156a-4992-ad7b-8212814269fc">

**Comment by Hugo-Dz** [comment]
Thanks for the report! Have you tried Node 16? And what is the Python version on your machine?

**Comment by dusskapark** [comment]
<img width="1000" alt="Screenshot 2023-06-12 at 12 03 12 PM" src="https://github.com/Hugo-Dz/figma_autoname_client_app/assets/4177529/a1249518-7614-4472-a459-58d87e4139b5">

I can run the plugin environment without any problems after changing the node version to 18.16 → 16.20, and then I forced the node-sass using the method in [this StackOverflow link](https://stackoverflow.com/questions/51777468/npm-error-when-trying-to-install-node-sass). 

The result: 
----
<img width="418" alt="Screenshot 2023-06-12 at 12 04 49 PM" src="https://github.com/Hugo-Dz/figma_autoname_client_app/assets/4177529/9c0f66c7-96c3-4d68-8755-e2465f378f81">


I would like you to create a troubleshooting section on your Readme or Wiki space to leave this issue link for others with similar problems with me. :)

**Comment by Hugo-Dz** [comment]
Yes! could you make a pr? :)

**Comment by dusskapark** [comment]
Okay. I'll make a PR as soon as possible including this and one my
suggestion I'm thinking of now.

2023년 6월 12일 (월) 오후 11:01, Hugo-Dz ***@***.***>님이 작성:
