### ISSUE TITLE
Request for the environment Variables(.env) of Svelte 

### ISSUE THREAD

**Issue by dusskapark** [Hugo-Dz/figma_autoname_client_app#7]
Hi @Hugo-Dz 

<img width="584" alt="Screenshot 2023-07-20 at 2 08 38 PM" src="https://github.com/Hugo-Dz/figma_autoname_client_app/assets/4177529/0924c9e6-d443-418c-99be-78a8e24104ae">

I'd like to request one thing to you. I guess people maybe need to set up the environment variables (.env) to configure their Default URL easily. I tried to follow the guide below, but I faced errors in VScode above. 

https://kit.svelte.dev/docs/modules#$env-dynamic-public

I'm confident you can help me resolve this issue, so I'm making this request.

**Comment by Hugo-Dz** [comment]
> 

@dusskapark The Svelte app doesn't use Vite here, it's a custom implementation with Rollup, you need to use the dotenv Rollup plugin in order to use env variables, you can check how to do it in this branch: https://github.com/Hugo-Dz/figma_autoname_client_app/tree/feat-env-var

**Comment by dusskapark** [comment]
Thanks @Hugo-Dz  ! I will commit this update by adding it to the PR you are currently reviewing.
