### ISSUE TITLE
base64 converting issue 

### ISSUE THREAD

**Issue by dusskapark** [Hugo-Dz/figma_autoname_client_app#9]
<img width="289" alt="Screenshot 2023-07-23 at 5 13 11 PM" src="https://github.com/Hugo-Dz/figma_autoname_client_app/assets/4177529/7bc354fb-934b-405d-bbaa-cf04f52e6ad1">
<img width="503" alt="Screenshot 2023-07-23 at 5 15 53 PM" src="https://github.com/Hugo-Dz/figma_autoname_client_app/assets/4177529/f3bf263a-4ee5-4db2-bb9c-58425fba9527">

I sent the results value from ui.svelte to code.ts and stored it in client storage by stringifying it.

Other strings are not a problem, but the image data byte in Unit8Array cannot be used properly.

If you know how to solve this problem, please let me know.

https://github.com/Hugo-Dz/figma_autoname_client_app/pull/8/files#r1271413443

```
const base64Data = btoa(String.fromCharCode.apply(null, bytes));
```

**Comment by dusskapark** [comment]
Here's the code I use to store the imageDataBytes in clientStorage:
```
const dataStoredAsString = JSON.stringify(predictionResult);
await figma.clientStorage.setAsync(node.id, dataStoredAsString);
```

And here's the code I use to retrieve and render the imageDataBytes:

```
if (event.data.pluginMessage.type === "updateSelection") {
  selectionInDevMode = event.data.pluginMessage.payload;

  if (selectionInDevMode !== "none") {
    selectionInDevModeData = JSON.parse(selectionInDevMode);
    sampleImage = await renderUint8ArrayToImage(
      selectionInDevModeData.imageDataBytes
    );
  }
}
```

The issue seems to be caused by JSON.stringify() not correctly serializing binary data like Uint8Array. Consequently, when I parse the stored data using JSON.parse(), the imageDataBytes are not properly restored...

And I have no idea how to handle this image byte without encountering this problem TT.

**Comment by sonnylazuardi** [comment]
Try to save the src string instead of image object. `JSON.stringify` doesnt work with `Image` object

![image](https://github.com/Hugo-Dz/figma_autoname_client_app/assets/856609/da7c11a0-a75e-4678-b7c0-c8340991bce5)

![image](https://github.com/Hugo-Dz/figma_autoname_client_app/assets/856609/f7f03ff9-5a36-4933-a96a-026dc6cd18ae)


```typescript

async function renderUint8ArrayToImageSrc( bytes: Uint8Array ): Promise<string> {
  const base64Data =  btoa(String.fromCharCode.apply(null, bytes)); 
  return "data:image/png;base64," + base64Data; 
}
```
